### ISSUE TITLE
Wrong TE connector

### ISSUE THREAD

**Issue by Martoni** [KiCad/Sockets.pretty#6]
The connector named Socket_SODIMM_DDR3_TE_2013289.kicad_mod is a copy from connector Socket_SODIMM_DDR1-2_TE_1612618.kicad_mod.

These two connectors have not the same footprint. Then Socket_SODIMM_DDR3_TE_2013289.kicad_mod is wrong. Specially the two laterals pad.

**Comment by evanshultz** [comment]
@Martoni Thanks for bringing this up. Indeed, mismatched footprints would be a problem.

2013289 datasheet: http://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=2013289&DocType=Customer+Drawing&DocLang=English

1612618 datasheet: http://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1612618&DocType=Customer+Drawing&DocLang=English

Counting down from pin 1, 2013289 has 36 pins in each row before the "break" while the other has 20 pins. This seems to match the footprints I see in KiCad:
![image](https://user-images.githubusercontent.com/1936989/28938287-7a6c3608-7842-11e7-9cb7-34768581707c.png)

While these footprints aren't KLC compliant, they appear to match their respective TE PNs. It's quite possible these footprints have been fixed since your issue was opened over a year ago. I'll leave this case open for a day before closing it in case you want to provide feedback.

**Comment by evanshultz** [comment]
No response above, problem seems resolved. Closing issue.
